

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=
spring.jpa.show-sql=
spring.jooq.sql-dialect=


jwt.secret=
jwt.expiration=


# GOOGLE
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=

# GITHUB
spring.security.oauth2.client.registration.github.client-id=
spring.security.oauth2.client.registration.github.client-secret=
spring.security.oauth2.client.registration.github.scope=

# REDIRECT
spring.security.oauth2.client.registration.google.redirect-uri=
spring.security.oauth2.client.registration.github.redirect-uri=